#!/usr/bin/env node

import fs from 'node:fs';
import path from 'node:path';
import { fileURLToPath } from 'node:url';

const __filename = fileURLToPath(import.meta.url);
const __dirname = path.dirname(__filename);
const rootDir = path.resolve(__dirname, '..');

const packageJsonPath = path.join(rootDir, 'package.json');
const packageLockPath = path.join(rootDir, 'package-lock.json');
const versionTsPath = path.join(rootDir, 'src', 'lib', 'version.ts');

const pkg = JSON.parse(fs.readFileSync(packageJsonPath, 'utf-8'));
const currentVersion = pkg.version || '0.0.1';

const mode = process.argv[2] || 'patch';

let newVersion = currentVersion;

const parts = currentVersion.split('.').map((p) => parseInt(p, 10) || 0);
while (parts.length < 3) parts.push(0);

if (mode === 'major') {
  parts[0] += 1;
  parts[1] = 0;
  parts[2] = 0;
  newVersion = parts.join('.');
} else if (mode === 'minor') {
  parts[1] += 1;
  parts[2] = 0;
  newVersion = parts.join('.');
} else if (mode === 'patch') {
  parts[2] += 1;
  newVersion = parts.join('.');
} else if (/^\d+\.\d+\.\d+/.test(mode)) {
  newVersion = mode;
} else {
  console.error(`Unknown bump mode: ${mode}. Use 'patch', 'minor', 'major', or a semver string like '0.1.0'.`);
  process.exit(1);
}

// Update package.json
pkg.version = newVersion;
fs.writeFileSync(packageJsonPath, JSON.stringify(pkg, null, '\t') + '\n', 'utf-8');

// Update package-lock.json if it exists
if (fs.existsSync(packageLockPath)) {
  try {
    const lock = JSON.parse(fs.readFileSync(packageLockPath, 'utf-8'));
    lock.version = newVersion;
    if (lock.packages && lock.packages['']) {
      lock.packages[''].version = newVersion;
    }
    fs.writeFileSync(packageLockPath, JSON.stringify(lock, null, '\t') + '\n', 'utf-8');
  } catch (err) {
    console.warn('[bump-version] Warning: Failed to update package-lock.json:', err.message);
  }
}

// Update src/lib/version.ts
const versionTsContent = `// This file is auto-generated by scripts/bump-version.js
export const APP_VERSION = '${newVersion}';
`;

fs.mkdirSync(path.dirname(versionTsPath), { recursive: true });
fs.writeFileSync(versionTsPath, versionTsContent, 'utf-8');

console.log(`[bump-version] Bumped version from ${currentVersion} to ${newVersion}`);
